# Generated by Django 3.0.5 on 2020-04-04 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='threadmanage',
            name='task',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
